"""
export_new_models.py — emit float-C headers for AI-6/7/8/9/10 (CIMC Lab-Sentinel)
=================================================================================
Loads the 4 trained MLPs (.pt) + builds the AI-9 retrieval DB, and emits
hand-written-float-C weight headers into firmware/ai_models_c/, plus host golden
headers into model/host_test/. Mirrors the export style of AI-4/AI-5.

Design choice (keeps the MCU side as pure matrix ops, no formula parser):
  AI-6/7 take a 24-D formula descriptor; AI-9 a 18-D recipe vector. Those are
  PRECOMPUTED on PC for a small set of recipe PRESETS and shipped in
  recipe_presets.h. The on-device engine just runs the MLP / kNN on the preset's
  vector (selected by recipe index). AI-8 computes its 5 features from the recipe
  temps/hours directly (already on-device). AI-10 computes 8 features from a live
  vibration window on-device.

Run:  cd CIMC/model && python export_new_models.py
"""

import csv
import json
import re
import sys
from pathlib import Path

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "CIMC" / "model" / "ai6_ts_optical"))
sys.path.insert(0, str(ROOT / "CIMC" / "model" / "ai7_thermal"))
sys.path.insert(0, str(ROOT / "CIMC" / "model" / "ai8_energy"))
sys.path.insert(0, str(ROOT / "CIMC" / "model" / "ai10_vibration"))

from predict_engine import ts_torch as T                  # noqa: E402
from distill_ts_optical import OpticalMLP, guess_site       # noqa: E402
from distill_thermal import ThermalMLP                      # noqa: E402
from distill_energy import EnergyMLP, feats as energy_feats, CO2_PER_KWH, P_MAX  # noqa: E402
from train_vib_pdm import VibMLP, synth_window, features as vib_features  # noqa: E402

OUT = ROOT / "CIMC" / "firmware" / "ai_models_c"
HOST = ROOT / "CIMC" / "model" / "host_test"
M = ROOT / "CIMC" / "model"

# AI-9 recipe vector (18-D) — matches ai9_retrieval sanity script
FLAGS = ["Ga", "Sc", "Mg", "Si", "Zr", "Lu", "Ca", "Sr", "Ba", "Ge", "La", "Al", "Y", "Gd"]


def carr(name, arr):
    flat = np.asarray(arr, np.float32).reshape(-1)
    return f"static const float {name}[{flat.size}] = {{ {', '.join(f'{v:.8e}f' for v in flat)} }};\n"


def els(fm):
    return set(re.findall(r"[A-Z][a-z]?", fm or ""))


def recipe18(formula, dopant, pct, temp, hours):
    e = els(formula)
    v = [1.0 if dopant == "Cr" else 0.0, pct / 2.0, temp / 1600.0, hours / 10.0]
    for x in FLAGS:
        v.append(1.0 if x in e else 0.0)
    return np.array(v, np.float32)


def mlp_layers(model):
    """Return list of (W[out,in], b[out]) for each nn.Linear in model.net."""
    L = []
    for m in model.net:
        if isinstance(m, torch.nn.Linear):
            L.append((m.weight.detach().numpy().astype(np.float32),
                      m.bias.detach().numpy().astype(np.float32)))
    return L


# --------------------------------------------------------------------------- AI-6/7
def export_optical_thermal():
    o = OpticalMLP(); od = torch.load(M / "ai6_ts_optical" / "ai6_optical.pt", map_location="cpu", weights_only=True)
    o.load_state_dict(od["model_state_dict"]); o.eval()
    th = ThermalMLP(); td = torch.load(M / "ai7_thermal" / "ai7_thermal.pt", map_location="cpu", weights_only=True)
    th.load_state_dict(td["model_state_dict"]); th.eval()

    oL = mlp_layers(o); tL = mlp_layers(th)
    s = ("/* AI-6 optical surrogate (24-D formula descriptor -> [lambda_em_nm, FWHM_nm]).\n"
         " * Distilled from the VALIDATED predict_engine ts_torch TSPredictor (6.2nm).\n"
         " * AUTO-GENERATED by export_new_models.py. */\n#ifndef AI6_OPTICAL_WEIGHTS_H\n#define AI6_OPTICAL_WEIGHTS_H\n\n"
         "#define AI6_IN 24\n#define AI6_H 32\n#define AI6_OUT 2\n")
    for i, (W, b) in enumerate(oL):
        s += carr(f"ai6_w{i}", W) + carr(f"ai6_b{i}", b)
    s += carr("ai6_out_mu", od["ymu"]) + carr("ai6_out_sd", od["ysd"])
    s += "\n#endif\n"
    (OUT / "ai6_optical_weights.h").write_text(s, encoding="utf-8")

    s = ("/* AI-7 thermal-quenching surrogate (24-D descriptor -> thermal_stability_pct@150C).\n"
         " * Distilled from Struck-Fonger physics; coarse (real ~17%) -> 3-band indicator.\n"
         " * AUTO-GENERATED. */\n#ifndef AI7_THERMAL_WEIGHTS_H\n#define AI7_THERMAL_WEIGHTS_H\n\n"
         "#define AI7_IN 24\n#define AI7_H 16\n#define AI7_OUT 1\n")
    for i, (W, b) in enumerate(tL):
        s += carr(f"ai7_w{i}", W) + carr(f"ai7_b{i}", b)
    s += f"static const float ai7_out_mu = {td['ymu']:.8e}f;\nstatic const float ai7_out_sd = {td['ysd']:.8e}f;\n"
    s += "\n#endif\n"
    (OUT / "ai7_thermal_weights.h").write_text(s, encoding="utf-8")
    return o, th, od, td


# --------------------------------------------------------------------------- AI-8
def export_energy():
    m = EnergyMLP(); d = torch.load(M / "ai8_energy" / "ai8_energy.pt", map_location="cpu", weights_only=True)
    m.load_state_dict(d["model_state_dict"]); m.eval()
    L = mlp_layers(m)
    s = ("/* AI-8 energy/carbon surrogate (5 recipe feats -> kWh; CO2 = kWh*factor).\n"
         " * Labels from nominal 5kW muffle-furnace physics; CO2 factor = China grid avg.\n"
         " * AUTO-GENERATED. */\n#ifndef AI8_ENERGY_WEIGHTS_H\n#define AI8_ENERGY_WEIGHTS_H\n\n"
         "#define AI8_IN 5\n#define AI8_H 16\n#define AI8_OUT 1\n")
    for i, (W, b) in enumerate(L):
        s += carr(f"ai8_w{i}", W) + carr(f"ai8_b{i}", b)
    s += (f"static const float ai8_out_mu = {d['ymu']:.8e}f;\nstatic const float ai8_out_sd = {d['ysd']:.8e}f;\n"
          f"static const float ai8_co2_per_kwh = {CO2_PER_KWH:.6f}f;\n"
          f"static const float ai8_p_max_kw = {P_MAX:.4f}f;\n")
    s += "\n#endif\n"
    (OUT / "ai8_energy_weights.h").write_text(s, encoding="utf-8")
    return m, d


# --------------------------------------------------------------------------- AI-10
def export_vib(emit_golden=True):
    m = VibMLP(); d = torch.load(M / "ai10_vibration" / "ai10_vib.pt", map_location="cpu", weights_only=True)
    m.load_state_dict(d["model_state_dict"]); m.eval()
    L = mlp_layers(m)
    s = ("/* AI-10 vibration PdM (8 feats -> 4 logits: normal/imbalance/bearing/looseness).\n"
         " * Synthetic ISO20816 signatures (real ADXL345 refine pending). AUTO-GENERATED. */\n"
         "#ifndef AI10_VIB_WEIGHTS_H\n#define AI10_VIB_WEIGHTS_H\n\n"
         "#define AI10_IN 8\n#define AI10_H 16\n#define AI10_OUT 4\n")
    for i, (W, b) in enumerate(L):
        s += carr(f"ai10_w{i}", W) + carr(f"ai10_b{i}", b)
    s += carr("ai10_in_mu", d["mu"]) + carr("ai10_in_sd", d["sd"])
    s += "\n#endif\n"
    (OUT / "ai10_vib_weights.h").write_text(s, encoding="utf-8")

    if emit_golden:
        # one deterministic imbalance window (class 1) + python features + raw logits
        rng = np.random.default_rng(123)
        win = synth_window(1, rng).astype(np.float32)
        f8 = vib_features(win).astype(np.float32)
        mu = np.array(d["mu"], np.float32); sd = np.array(d["sd"], np.float32)
        with torch.no_grad():
            logits = m(torch.tensor((f8 - mu) / sd)[None]).numpy().reshape(-1)
        cls = int(np.argmax(logits))
        g = ("/* AI-10 golden: a synthetic imbalance window + python feats + raw logits.\n"
             " * AUTO-GENERATED. */\n#ifndef AI10_GOLDEN_H\n#define AI10_GOLDEN_H\n\n")
        g += carr("g_ai10_window", win) + carr("g_ai10_feat8", f8) + carr("g_ai10_logits", logits)
        g += f"static const int g_ai10_cls = {cls};\n\n#endif\n"
        (OUT / "ai10_golden.h").write_text(g, encoding="utf-8")
        (HOST / "ai10_golden.h").write_text(g, encoding="utf-8")
        print(f"[golden] AI-10 window->feat8={np.round(f8,3)} logits={np.round(logits,3)} cls={cls}")
    return m, d


# --------------------------------------------------------------------------- AI-9 DB
OUTCOME = {"unknown": 0, "pure": 1, "mixed": 2, "amorphous": 3}


def export_retrieval_db():
    rows = list(csv.DictReader(open(ROOT / "exp_ground_truth" / "observed_pl.csv", encoding="utf-8")))
    feats, names, oc, lam = [], [], [], []
    for r in rows:
        fm = (r.get("formula") or "").strip()
        if not fm:
            continue
        dop = (r.get("dopant_element") or "Cr").strip()
        pct = float(r.get("dopant_pct") or 1.0)
        temp = float(r.get("sinter_temp_C") or 1400.0)
        hrs = float(r.get("sinter_hours") or 5.0)
        feats.append(recipe18(fm, dop, pct, temp, hrs))
        names.append(fm)
        oc.append(OUTCOME.get((r.get("xrd_result") or "unknown").strip(), 0))
        le = (r.get("lambda_em_nm") or "").strip()
        lam.append(float(le) if le not in ("", "nan") else -1.0)
    F = np.stack(feats); sd = F.std(0) + 1e-6
    n, d = F.shape
    s = ("/* AI-9 recipe analog retrieval DB: 67 real observed_pl recipes (18-D each)\n"
         " * + outcome code (0 unknown/1 pure/2 mixed/3 amorphous) + lambda_em (-1=none).\n"
         " * On-device kNN: dist = sum(((q-ref)/sd)^2). Shows analogs, NOT a prediction.\n"
         " * AUTO-GENERATED. */\n#ifndef AI9_RECIPE_DB_H\n#define AI9_RECIPE_DB_H\n\n"
         f"#define AI9_N {n}\n#define AI9_D {d}\n\n")
    s += carr("ai9_ref", F)            # [N*D] row-major
    s += carr("ai9_sd", sd)            # [D]
    s += "static const unsigned char ai9_outcome[%d] = { %s };\n" % (n, ", ".join(str(x) for x in oc))
    s += carr("ai9_lambda", lam)       # [N]
    # outcome name strings + formula names (for HMI)
    s += "static const char *const ai9_oc_name[4] = { \"unknown\", \"pure\", \"mixed\", \"amorph\" };\n"
    s += "static const char *const ai9_name[%d] = { %s };\n" % (n, ", ".join('"%s"' % x for x in names))
    s += "\n#endif\n"
    (OUT / "ai9_recipe_db.h").write_text(s, encoding="utf-8")
    return F, sd, names, oc, lam


# --------------------------------------------------------------------------- presets + golden
def export_presets_and_golden(o, th, od, td, en, ed, F, sd):
    # recipe presets: (display, formula, dopant, site, pct, calcT, calcH, sintT, sintH, ramp)
    PRESETS = [
        ("YAG:Cr garnet",   "Y3Al5O12",  "Cr", "Al", 1.0, 900, 4, 1500, 6, 5.0),
        ("GAGG:Cr garnet",  "Gd3Al2Ga3O12", "Cr", "Ga", 1.0, 900, 4, 1450, 6, 5.0),
        ("Y3Ga5O12:Cr",     "Y3Ga5O12",  "Cr", "Ga", 1.5, 900, 4, 1450, 6, 5.0),
        ("Mg2SiO4:Cr",      "Mg2SiO4",   "Cr", "Mg", 1.0, 1000, 4, 1400, 6, 5.0),
    ]
    desc_rows, r18_rows, e5_rows, labels = [], [], [], []
    for (disp, fm, dop, site, pct, cT, cH, sT, sH, rp) in PRESETS:
        desc_rows.append(T.formula_descriptor(fm, site, pct).numpy())
        r18_rows.append(recipe18(fm, dop, pct, sT, sH))
        e5_rows.append(energy_feats(cT, cH, sT, sH, rp))
        labels.append(disp)
    s = ("/* recipe_presets.h — PC-precomputed feature vectors for AI-6/7/8/9.\n"
         " * AI-6/7 need a 24-D formula descriptor, AI-9 a 18-D recipe vector — both are\n"
         " * deterministic from the recipe, so precomputed here (no MCU formula parser).\n"
         " * AI-8 5-D feats are recomputable on-device from temps/hours but shipped too.\n"
         " * AUTO-GENERATED. */\n#ifndef RECIPE_PRESETS_H\n#define RECIPE_PRESETS_H\n\n"
         f"#define N_PRESET {len(PRESETS)}\n#define PRESET_DESC 24\n#define PRESET_R18 18\n\n")
    s += carr("preset_desc", np.stack(desc_rows))   # [N*24]
    s += carr("preset_r18", np.stack(r18_rows))     # [N*18]
    s += carr("preset_e5", np.stack(e5_rows))       # [N*5]
    s += "static const char *const preset_name[%d] = { %s };\n" % (
        len(PRESETS), ", ".join('"%s"' % x for x in labels))
    # also ship the raw recipe params (for AI-8 live + display)
    pr = np.array([[cT, cH, sT, sH, rp] for (_, _, _, _, _, cT, cH, sT, sH, rp) in PRESETS], np.float32)
    s += carr("preset_recipe", pr)                  # [N*5] calcT,calcH,sintT,sintH,ramp
    s += "\n#endif\n"
    (OUT / "recipe_presets.h").write_text(s, encoding="utf-8")

    # ---- golden: run each model on preset 0 (YAG:Cr), store DENORMED physical outputs ----
    omu, osd = np.array(od["ymu"], np.float32), np.array(od["ysd"], np.float32)
    with torch.no_grad():
        d0 = torch.tensor(desc_rows[0])[None]
        ai6_raw = o(d0).numpy().reshape(-1)
        ai6_phys = ai6_raw * osd + omu                       # [lambda_em, FWHM] nm
        ai7_pct = float(th(d0).numpy().reshape(-1)[0]) * td["ysd"] + td["ymu"]
        e0 = torch.tensor(e5_rows[0])[None]
        ai8_kwh = max(0.0, float(en(e0).numpy().reshape(-1)[0]) * ed["ysd"] + ed["ymu"])
    g = ("/* golden for AI-6/7/8/9 engines (preset 0 = YAG:Cr), DENORMED physical outputs\n"
         " * (lambda_em nm / FWHM nm / thermal % / kWh) — compare engine output directly. AUTO-GEN. */\n"
         "#ifndef NEW_MODELS_GOLDEN_H\n#define NEW_MODELS_GOLDEN_H\n\n")
    g += carr("g_ai6_desc", desc_rows[0])
    g += f"static const float g_ai6_lambda = {ai6_phys[0]:.6f}f;\nstatic const float g_ai6_fwhm = {ai6_phys[1]:.6f}f;\n"
    g += f"static const float g_ai7_pct = {ai7_pct:.6f}f;\n"
    g += carr("g_ai8_e5", e5_rows[0]) + f"static const float g_ai8_kwh = {ai8_kwh:.6f}f;\n"
    q = r18_rows[0]
    dist = np.sum(((q[None] - F) / sd) ** 2, axis=1)
    nn = int(np.argmin(dist))
    g += carr("g_ai9_query", q) + f"static const int g_ai9_nn = {nn};\n"
    g += "\n#endif\n"
    (OUT / "new_models_golden.h").write_text(g, encoding="utf-8")
    (HOST / "new_models_golden.h").write_text(g, encoding="utf-8")
    print(f"[golden] AI-6 lambda={ai6_phys[0]:.1f}nm FWHM={ai6_phys[1]:.1f}nm  AI-7 {ai7_pct:.1f}%  "
          f"AI-8 {ai8_kwh:.1f}kWh  AI-9 nn={nn} ({labels[0]}~DB[{nn}])")


def main():
    o, th, od, td = export_optical_thermal()
    en, ed = export_energy()
    export_vib()
    F, sd, names, oc, lam = export_retrieval_db()
    export_presets_and_golden(o, th, od, td, en, ed, F, sd)
    print("[done] wrote ai6/ai7/ai8/ai10 weights + ai9_recipe_db + recipe_presets + golden ->", OUT)


if __name__ == "__main__":
    main()
