"""
int8_export.py — B1 on-chip INT8 inference path for AI-12 (CIMC Lab-Sentinel)
=============================================================================
Demonstrates a deployable weight-only INT8 path on the GD32 M7 (honest scheme:
per-output-channel symmetric PTQ; biases stay fp32; compute stays float because the
M7 has no int8 SIMD — the win is 4x Flash + less weight D-cache traffic). Mirrors the
analysis in quantize_compare.py, but here we EMIT the int8 weights + a golden so the
on-chip int8 engine (ai12_plclass_int8) is host-verified to agree with fp32.

Run:  cd CIMC/model && python int8_export.py
Out:  firmware/ai_models_c/ai12_int8_weights.h
      firmware/ai_models_c/int8_golden.h  (+ host_test copy)
"""
import sys
from pathlib import Path

import numpy as np
import torch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE / "ai12_plspec"))
from train_plspec import load_dataset, SpecMLP  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "CIMC" / "firmware" / "ai_models_c"
HOST = ROOT / "CIMC" / "model" / "host_test"


def quant_per_out(W):
    """W[out,in] float -> (int8 Wq[out,in], scale[out]) per-output symmetric PTQ."""
    s = np.max(np.abs(W), axis=1) / 127.0
    s[s == 0] = 1e-12
    Wq = np.clip(np.round(W / s[:, None]), -127, 127).astype(np.int8)
    return Wq, s.astype(np.float32)


def i8arr(name, arr):
    flat = np.asarray(arr, np.int8).reshape(-1)
    return f"static const signed char {name}[{flat.size}] = {{ {', '.join(str(int(v)) for v in flat)} }};\n"


def farr(name, arr):
    flat = np.asarray(arr, np.float32).reshape(-1)
    return f"static const float {name}[{flat.size}] = {{ {', '.join(f'{v:.8e}f' for v in flat)} }};\n"


def fwd_fp32(X, Ws, bs):
    a = X
    for i, (W, b) in enumerate(zip(Ws, bs)):
        a = a @ W.T + b
        if i < len(Ws) - 1:
            a = np.maximum(a, 0)
    return a


def fwd_int8(X, Wqs, ss, bs):
    a = X
    for i, (Wq, s, b) in enumerate(zip(Wqs, ss, bs)):
        a = (a @ (Wq.astype(np.float32) * s[:, None]).T) + b
        if i < len(Wqs) - 1:
            a = np.maximum(a, 0)
    return a


def main():
    X, y, _ = load_dataset()
    m = SpecMLP()
    ck = torch.load(HERE / "ai12_plspec" / "ai12_plspec.pt",
                    map_location="cpu", weights_only=True)
    m.load_state_dict(ck["model_state_dict"]); m.eval()
    lin = [l for l in m.net if isinstance(l, torch.nn.Linear)]
    Ws = [l.weight.detach().numpy().astype(np.float32) for l in lin]
    bs = [l.bias.detach().numpy().astype(np.float32) for l in lin]

    Wqs, ss = zip(*(quant_per_out(W) for W in Ws))

    # accuracy: fp32 vs int8 on all 281 real spectra
    p32 = fwd_fp32(X, Ws, bs).argmax(1)
    p8 = fwd_int8(X, Wqs, ss, bs).argmax(1)
    acc32 = float((p32 == y).mean()); acc8 = float((p8 == y).mean())
    agree = float((p32 == p8).mean())
    l32 = fwd_fp32(X, Ws, bs); l8 = fwd_int8(X, Wqs, ss, bs)
    maxlogerr = float(np.max(np.abs(l32 - l8)))
    fp32_bytes = sum(W.size for W in Ws) * 4
    int8_bytes = sum(Wq.size for Wq in Wqs) + sum(s.size for s in ss) * 4
    print(f"[AI-12 INT8] fp32 acc {acc32*100:.1f}% | int8 acc {acc8*100:.1f}% | "
          f"agree {agree*100:.1f}% | max|logit err| {maxlogerr:.4f}")
    print(f"[AI-12 INT8] weight Flash {fp32_bytes} B (fp32) -> {int8_bytes} B (int8) "
          f"= {fp32_bytes/int8_bytes:.2f}x smaller")

    # emit int8 weights
    h = OUT / "ai12_int8_weights.h"
    with open(h, "w") as f:
        f.write("/* ai12_int8_weights.h - AUTO-GENERATED by int8_export.py (B1 quantisation)\n")
        f.write(" * AI-12 PL classifier, weight-only per-output symmetric INT8 PTQ.\n")
        f.write(f" * On 281 real spectra: fp32 {acc32*100:.1f}% vs int8 {acc8*100:.1f}% "
                f"(agree {agree*100:.1f}%), weights {fp32_bytes/int8_bytes:.2f}x smaller.\n")
        f.write(" * Biases stay fp32 (ai12_b0/b1/b2 in ai12_plspec_weights.h). */\n")
        f.write("#ifndef AI12_INT8_WEIGHTS_H\n#define AI12_INT8_WEIGHTS_H\n\n")
        for li, (Wq, s) in enumerate(zip(Wqs, ss)):
            f.write(i8arr(f"ai12_q_w{li}", Wq))
            f.write(farr(f"ai12_q_s{li}", s))
        f.write("\n#endif\n")
    print(f"[export] {h}")

    # golden: 8 spectra spanning classes; fp32 + int8 reference classes
    pick = []
    for c in (0, 1, 2):
        idx = list(np.where(y == c)[0])[:3]
        pick += idx
    gx = X[pick]
    g32 = fwd_fp32(gx, Ws, bs).argmax(1)
    g8 = fwd_int8(gx, Wqs, ss, bs).argmax(1)
    g = OUT / "int8_golden.h"
    with open(g, "w") as f:
        f.write("/* int8_golden.h - AUTO-GENERATED. AI-12 fp32-vs-int8 golden. */\n")
        f.write("#ifndef INT8_GOLDEN_H\n#define INT8_GOLDEN_H\n\n")
        f.write(f"#define I8_NG {len(pick)}\n")
        f.write(f"#define I8_MAXLOGERR {maxlogerr:.6f}f\n\n")
        f.write(farr("i8_g_spec", gx))
        f.write(f"static const int i8_g_cls_fp32[{len(pick)}] = {{ {', '.join(str(int(v)) for v in g32)} }};\n")
        f.write(f"static const int i8_g_cls_int8[{len(pick)}] = {{ {', '.join(str(int(v)) for v in g8)} }};\n")
        f.write("\n#endif\n")
    import shutil
    shutil.copy(g, HOST / "int8_golden.h")
    print(f"[export] {g}  (+ host_test copy)")


if __name__ == "__main__":
    main()
