/* ai1_crucible.h — AI-1 crucible 3-class CNN (CIMC Lab-Sentinel)
 *
 * 3x64x64 float[0,1] CHW image -> CRU_NCLS(=3) logits. Returns argmax:
 *   0 empty / 1 loaded / 2 done.
 * Trained on real phone-shot crucible photos (CIMC/手机拍摄数据, 5-fold CV 90.7%).
 * ("sintering" / in-furnace glow is not a visual class — invisible from outside
 *  the furnace; the firmware's 4-stage furnace proxy carries that signal.)
 *
 * Hand-written float32 engine (ADR-1 fallback), BN folded into stride-2 convs.
 * ~3.9 M MACs; activations live in two static SRAM ping-pong buffers (~49 KB).
 * Weights in ai1_crucible_weights.h (AUTO-GENERATED by export_crucible_to_c.py).
 */
#ifndef AI1_CRUCIBLE_H
#define AI1_CRUCIBLE_H

/* img_chw: 3*64*64 floats in [0,1], channel-major (R plane, G plane, B plane).
 * logits_out: caller-provided float[>=CRU_NCLS] (CRU_NCLS=3 logits written).
 * emb_out32 : caller-provided float[32] = the GAP feature vector (the 32-D image
 *             embedding consumed by the AI-1b few-shot NCM classifier). May be
 *             NULL if the embedding is not needed.
 * Returns argmax class index 0..2 (0 empty / 1 loaded / 2 done). */
int ai1_crucible_forward(const float *img_chw, float *logits_out, float *emb_out32);

/* B3 explainability: Class Activation Map for the predicted class (forward-only,
 * since AI-1 ends in GAP->FC). cam16 = caller-provided float[16] = a 4x4 heatmap
 * (row-major), ReLU + max-normalised to [0,1], over the crucible crop. Returns the
 * predicted class 0..2. ~512 extra MACs on the forward pass. */
int ai1_crucible_cam(const float *img_chw, float *cam16);

#endif /* AI1_CRUCIBLE_H */
