/* ai4_calib.h  --  AUTO-GENERATED by calibrate_abstain.py.
 * AI-4 confidence calibration (temperature scaling) + abstention scalars.
 *   calibrated probs = softmax(logits / AI4_TEMP)
 *   abstain (flag for operator review) when max prob < AI4_ABSTAIN_CONF
 * Source: ai4_fusion.pt logits on X_fusion_test.npy (Guo 2017). */
#ifndef AI4_CALIB_H
#define AI4_CALIB_H

#define AI4_TEMP          1.00000000e+00f
#define AI4_ABSTAIN_CONF  9.50000000e-01f

#endif /* AI4_CALIB_H */
