/* ai5_golden.h -- AI-5 golden vector for on-chip self-test.
 * AUTO-GENERATED by export_ai5_to_c.py. Fixed 27-D input + PyTorch eval-mode
 * logits; the firmware runs its C engine and checks max|err| < tol.
 * Included only by the self-test / host harness (keeps ai5_diagnose.c -Wall clean). */
#ifndef AI5_GOLDEN_H
#define AI5_GOLDEN_H

static const float g_ai5_input[27] = { 5.69753468e-01f, 6.17698908e-01f, 6.83944345e-01f, 1.01976015e-01f, 5.31476974e+00f, 3.00441794e-02f, 4.63043660e-01f, 2.74539739e-01f, 1.60553962e-01f, 7.84755647e-02f, 1.52116209e-01f, 9.83762383e-01f, 9.69376504e-01f, 2.09776625e-01f, 2.86220554e-02f, 8.40856254e-01f, 2.82929987e-01f, 2.90034235e-01f, 7.04960167e-01f, 3.98797601e-01f, 7.37786829e-01f, 7.44114280e-01f, 5.53455353e-01f, 7.22552419e-01f, 1.53117582e-01f, 4.80373234e-01f, 1.97393224e-01f };
static const float g_ai5_logits[9] = { -8.30093670e+00f, -3.33441401e+00f, -1.01037312e+01f, -2.16578746e+00f, -6.32388687e+00f, -5.18157387e+00f, -3.43399256e-01f, 1.45959944e-01f, 3.37501192e+00f };

#endif /* AI5_GOLDEN_H */
