/* nlm_bank_prov.h - AUTO-GENERATED by export_lmbank.py. SPI-flash placement of
 * the LM size bank, for both the swap-load engine and UART provisioning.
 * Standalone (no vocab) so flash_provision.c stays clear of NLM_* dim macros. */
#ifndef NLM_BANK_PROV_H
#define NLM_BANK_PROV_H
#define BANK_PROV_BASE  0x540000u   /* SPI flash byte offset of the bank image */
#define BANK_PROV_BYTES 2330624u        /* padded image size = UART provisioning total */
#endif
