"""
gen_corpus.py — build the DeepSeek distillation corpus for the GD32 nano-LM.

Pipeline role (ADR-1: PC/5090 trains, MCU only runs the text artifact):
  Enumerate realistic furnace/sentinel STATES (12 categorical slots) ->
  describe each in Chinese -> ask DeepSeek (a large teacher model family)
  for a ONE-SENTENCE diagnosis+action -> save (slots, sentence) pairs.

The 12-slot schema here is the CONTRACT shared with the firmware: the C side
emits the same control-token IDs from the live sentinel snapshot, so the on-chip
nano-LM sees exactly the distribution it was distilled on. Keep SLOTS in sync
with ai_nanolm build_context() (exported as named constants in nanolm_vocab.h).

Honesty: every sentence is generated by DeepSeek (knowledge distillation), not
hand-written templates. States are physically plausible (fault<->stage<->gas
correlations encoded below), so the teacher never sees nonsense inputs.

Run (on the 5090):
  python3 gen_corpus.py --n 3600 --workers 24 --out corpus.jsonl
  python3 gen_corpus.py --smoke            # 6 calls, print samples, no file
"""
import argparse
import json
import os
import random
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed

DEEPSEEK_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_URL = "https://api.deepseek.com/chat/completions"
# The provider retired the legacy deepseek-chat alias in July 2026. Keep the
# endpoint selectable for future API revisions without editing source code.
MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-v4-flash")

SYS_PROMPT = (
    "你是部署在近红外荧光粉烧结炉旁的边缘AI诊断助手(运行在单片机上)。"
    "根据给定的实时炉况状态,用一句话给出最关键的诊断结论和操作建议。"
    "要求:不超过28个汉字;专业、具体、可执行;直接给结论,不要解释推理过程;"
    "不要使用除标点外的英文字母和数字单位以外的英文;不要换行;不要加引号。"
)

# ── 12-slot state schema (CONTRACT with firmware build_context) ────────────────
# Each slot: key -> (token_suffix, chinese_phrase). Token name = SLOT + '_' + suffix.
SLOTS = {
    "stage": {
        "idle":    ("IDLE",    "待机(炉冷)"),
        "preheat": ("PREHEAT", "预热升温"),
        "calcine": ("CALCINE", "煅烧保温"),
        "ramp":    ("RAMP",    "升温中"),
        "sinter":  ("SINTER",  "高温烧结"),
        "cool":    ("COOL",    "降温冷却"),
        "done":    ("DONE",    "出炉完成"),
    },
    "risk": {
        "good": ("GOOD", "正常"),
        "warn": ("WARN", "注意"),
        "bad":  ("BAD",  "异常"),
        "crit": ("CRIT", "严重"),
    },
    "ramp": {
        "ok":   ("OK",   "平稳"),
        "fast": ("FAST", "过快"),
        "slow": ("SLOW", "过慢"),
    },
    "drift": {
        "ok": ("OK", "稳定"),
        "hi": ("HI", "温漂偏大"),
    },
    "tc": {
        "ok":    ("OK",    "正常"),
        "open":  ("OPEN",  "断路(开路)"),
        "short": ("SHORT", "短路"),
    },
    "gas": {
        "ok":    ("OK",    "气氛正常"),
        "cr6":   ("CR6",   "检测到Cr6+氧化风险"),
        "hf":    ("HF",    "检测到HF/含氟分解气"),
        "co2":   ("CO2",   "检测到CO2(碳酸盐分解)"),
        "moist": ("MOIST", "湿度偏高/受潮"),
    },
    "ae": {
        "ok":   ("OK",   "烧结曲线正常"),
        "anom": ("ANOM", "烧结曲线AE异常"),
    },
    "vib": {
        "ok":   ("OK",   "无振动"),
        "run":  ("RUN",  "研磨振动正常"),
        "abn":  ("ABN",  "研磨/搬运振动异常"),
    },
    "energy": {
        "ok":   ("OK",   "能耗正常"),
        "high": ("HIGH", "能耗偏高"),
    },
    "host": {
        "yag":  ("YAG",  "YAG:Cr石榴石"),
        "gagg": ("GAGG", "GAGG:Cr石榴石"),
        "ggg":  ("GGG",  "GGG:Cr石榴石"),
        "y2o3": ("Y2O3", "Y2O3:Cr"),
        "sygo": ("SYGO", "SYGO:Cr新相"),
    },
    "elem": {
        "ok":    ("OK",    "加热元件健康"),
        "warn":  ("WARN",  "加热元件老化预警"),
        "alarm": ("ALARM", "加热元件寿命告警"),
    },
    "temp": {  # temperature bucket; numeric value filled per-sample for the prompt
        "rt":    ("RT",    "室温"),
        "t200":  ("T200",  "约200°C"),
        "t400":  ("T400",  "约400°C"),
        "t600":  ("T600",  "约600°C"),
        "t800":  ("T800",  "约800°C"),
        "t900":  ("T900",  "约900°C"),
        "t1000": ("T1000", "约1000°C"),
        "t1200": ("T1200", "约1200°C"),
        "t1400": ("T1400", "约1400°C"),
        "t1500": ("T1500", "约1500°C"),
        "over":  ("OVER",  "超温(>1530°C)"),
    },
}
SLOT_ORDER = ["stage", "temp", "risk", "ramp", "drift", "tc", "gas", "ae", "vib", "energy", "host", "elem"]

STAGE_TEMP = {  # plausible temp bucket per stage
    "idle": "rt", "preheat": "t400", "calcine": "t900", "ramp": "t1200",
    "sinter": "t1500", "cool": "t800", "done": "rt",
}
TEMP_NUM = {"rt": 25, "t200": 215, "t400": 430, "t600": 615, "t800": 820, "t900": 905,
            "t1000": 1010, "t1200": 1215, "t1400": 1415, "t1500": 1500, "over": 1560}


def base_state(stage, host):
    return {"stage": stage, "temp": STAGE_TEMP[stage], "risk": "good", "ramp": "ok",
            "drift": "ok", "tc": "ok", "gas": "ok", "ae": "ok", "vib": "ok",
            "energy": "ok", "host": host, "elem": "ok"}


# scenario -> (slot overrides, risk) ; applied on top of base_state
def scenarios(stage):
    """Physically plausible fault scenarios for a given stage."""
    sc = {"normal": ({}, "good")}
    if stage in ("ramp", "preheat"):
        sc["ramp_fast"] = ({"ramp": "fast", "ae": "anom"}, "bad")
        sc["ramp_slow"] = ({"ramp": "slow", "energy": "high"}, "warn")
    if stage in ("calcine", "sinter", "ramp"):
        sc["drift"] = ({"drift": "hi", "ae": "anom"}, "bad")
        sc["tc_open"] = ({"tc": "open", "temp": "rt"}, "crit")     # open TC reads cold
        sc["tc_short"] = ({"tc": "short", "temp": "over"}, "crit")  # short can read hot/erratic
        sc["elem_alarm"] = ({"elem": "alarm", "ramp": "slow", "energy": "high"}, "bad")
    if stage == "sinter":
        sc["gas_cr6"] = ({"gas": "cr6"}, "bad")          # Cr3+ -> Cr6+ oxidation > 900C
        sc["overtemp"] = ({"temp": "over", "drift": "hi"}, "crit")
    if stage == "calcine":
        sc["gas_co2"] = ({"gas": "co2"}, "warn")          # carbonate decomposition
    if stage in ("preheat", "calcine"):
        sc["gas_hf"] = ({"gas": "hf"}, "bad")             # NH4F / fluoride off-gas
        sc["moist"] = ({"gas": "moist", "drift": "hi"}, "warn")
    if stage in ("calcine", "sinter"):
        sc["vib_abn"] = ({"vib": "abn"}, "warn")          # grinding/transport vibration
    if stage in ("calcine", "sinter", "cool"):
        sc["elem_warn"] = ({"elem": "warn", "energy": "high"}, "warn")
    # a couple of compound faults
    if stage == "sinter":
        sc["cr6_drift"] = ({"gas": "cr6", "drift": "hi", "ae": "anom"}, "crit")
    return sc


def make_state(rng, stage, scen_name, scen):
    overrides, risk = scen
    host = rng.choice(list(SLOTS["host"].keys()))
    st = base_state(stage, host)
    st.update(overrides)
    st["risk"] = risk
    return st


def describe(st):
    """Human-readable Chinese description fed to DeepSeek."""
    parts = []
    parts.append(f"烧结阶段:{SLOTS['stage'][st['stage']][1]}")
    tnum = TEMP_NUM[st["temp"]]
    parts.append(f"炉温:约{tnum}°C")
    parts.append(f"综合风险:{SLOTS['risk'][st['risk']][1]}")
    parts.append(f"升温速率:{SLOTS['ramp'][st['ramp']][1]}")
    parts.append(f"温度漂移:{SLOTS['drift'][st['drift']][1]}")
    parts.append(f"热电偶:{SLOTS['tc'][st['tc']][1]}")
    parts.append(f"气氛:{SLOTS['gas'][st['gas']][1]}")
    parts.append(f"烧结曲线监测:{SLOTS['ae'][st['ae']][1]}")
    parts.append(f"振动:{SLOTS['vib'][st['vib']][1]}")
    parts.append(f"能耗:{SLOTS['energy'][st['energy']][1]}")
    parts.append(f"配方:{SLOTS['host'][st['host']][1]}")
    parts.append(f"加热元件:{SLOTS['elem'][st['elem']][1]}")
    return ";".join(parts) + "。"


def call_deepseek(desc, temperature=0.4, retries=4):
    if not DEEPSEEK_KEY:
        raise RuntimeError("DEEPSEEK_API_KEY is required; never hard-code it")
    body = json.dumps({
        "model": MODEL,
        "messages": [{"role": "system", "content": SYS_PROMPT},
                     {"role": "user", "content": "炉况状态:" + desc + "\n请给出一句话诊断与建议。"}],
        "temperature": temperature, "max_tokens": 80, "stream": False,
    }).encode("utf-8")
    for i in range(retries):
        try:
            req = urllib.request.Request(DEEPSEEK_URL, data=body, headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {DEEPSEEK_KEY}"})
            with urllib.request.urlopen(req, timeout=60) as r:
                d = json.loads(r.read().decode("utf-8"))
            txt = d["choices"][0]["message"]["content"].strip()
            txt = txt.replace("\n", "").replace("\r", "").strip().strip('"“”')
            return txt
        except Exception as ex:
            if i == retries - 1:
                return f"__ERR__{ex}"
            time.sleep(1.5 * (i + 1))


def build_states(n, seed=20260603):
    rng = random.Random(seed)
    stages = list(SLOTS["stage"].keys())
    states = []
    # coverage pass: every (stage, scenario) a few times
    for stage in stages:
        for scen_name, scen in scenarios(stage).items():
            reps = 8 if scen_name == "normal" else 6
            for _ in range(reps):
                states.append(make_state(rng, stage, scen_name, scen))
    # fill remainder with random (stage, scenario) draws
    while len(states) < n:
        stage = rng.choice(stages)
        scs = scenarios(stage)
        scen_name = rng.choice(list(scs.keys()))
        states.append(make_state(rng, stage, scen_name, scs[scen_name]))
    rng.shuffle(states)
    return states[:n]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=3600)
    ap.add_argument("--workers", type=int, default=24)
    ap.add_argument("--out", default="corpus.jsonl")
    ap.add_argument("--smoke", action="store_true")
    args = ap.parse_args()

    if args.smoke:
        rng = random.Random(1)
        demo = []
        for stage in ["sinter", "calcine", "ramp", "sinter", "idle", "cool"]:
            scs = scenarios(stage)
            name = rng.choice(list(scs.keys()))
            demo.append(make_state(rng, stage, name, scs[name]))
        for st in demo:
            desc = describe(st)
            out = call_deepseek(desc)
            print("STATE:", {k: st[k] for k in SLOT_ORDER})
            print("DESC :", desc)
            print("DIAG :", out)
            print("-" * 70)
        return

    states = build_states(args.n)
    print(f"built {len(states)} states; querying DeepSeek with {args.workers} workers...")
    t0 = time.time()
    rows = [None] * len(states)
    done = 0
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = {ex.submit(call_deepseek, describe(st)): i for i, st in enumerate(states)}
        for fut in as_completed(futs):
            i = futs[fut]
            txt = fut.result()
            rows[i] = (states[i], txt)
            done += 1
            if done % 200 == 0:
                print(f"  {done}/{len(states)}  ({time.time()-t0:.0f}s)")

    n_err = 0
    n_ok = 0
    with open(args.out, "w", encoding="utf-8") as f:
        for st, txt in rows:
            if txt.startswith("__ERR__") or not txt or len(txt) > 60:
                n_err += 1
                continue
            f.write(json.dumps({"slots": st, "text": txt}, ensure_ascii=False) + "\n")
            n_ok += 1
    print(f"done: {n_ok} ok, {n_err} dropped -> {args.out}  ({time.time()-t0:.0f}s)")


if __name__ == "__main__":
    main()
