"""
export_ai5_to_c.py  --  emit AI-5 root-cause diagnoser weights as hand-written-C
headers for the GD32H759 firmware (firmware/ai_models_c/), mirroring
export_weights_to_c.py (BN folded into the Linears, byte-for-byte verified).

Outputs:
  firmware/ai_models_c/ai5_diagnose_weights.h   weights (BN folded) + dims + class names
  firmware/ai_models_c/ai5_golden.h             golden input + expected logits (self-test)

Run: cd CIMC/model/ai5_rootcause && python export_ai5_to_c.py   (needs torch)
No fabricated constants: every number is a trained-weight value or a documented dim.
"""
import json
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn

HERE = Path(__file__).parent
OUT = HERE.parents[1] / "firmware" / "ai_models_c"
GOLDEN_SEED = 1234 + 5
N_FEAT, N_CLASSES = 27, 9


class DiagMLP(nn.Module):                      # must match train_ai5.py
    def __init__(self, n_feat=N_FEAT, n_classes=N_CLASSES, dropout=0.2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_feat, 32), nn.BatchNorm1d(32), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(32, 16),     nn.BatchNorm1d(16), nn.ReLU(), nn.Dropout(dropout),
            nn.Linear(16, n_classes),
        )

    def forward(self, x):
        return self.net(x)


def carr(name, arr):
    flat = np.asarray(arr, dtype=np.float32).reshape(-1)
    vals = ", ".join(f"{float(v):.8e}f" for v in flat)
    return f"static const float {name}[{flat.size}] = {{ {vals} }};\n"


def fold_bn(lin_w, lin_b, bn_w, bn_b, bn_mean, bn_var, eps=1e-5):
    s = bn_w / np.sqrt(bn_var + eps)
    return (lin_w * s[:, None]).astype(np.float32), ((lin_b - bn_mean) * s + bn_b).astype(np.float32)


def sd_np(sd, k):
    return sd[k].detach().cpu().numpy().astype(np.float32)


def main():
    ck = torch.load(HERE / "ai5_diagnose.pt", map_location="cpu", weights_only=True)
    sd = ck["model"]
    names = ck.get("class_names")
    m = DiagMLP(); m.load_state_dict(sd); m.eval()

    fc0_w, fc0_b = sd_np(sd, "net.0.weight"), sd_np(sd, "net.0.bias")
    bn0 = (sd_np(sd, "net.1.weight"), sd_np(sd, "net.1.bias"),
           sd_np(sd, "net.1.running_mean"), sd_np(sd, "net.1.running_var"))
    fc1_w, fc1_b = sd_np(sd, "net.4.weight"), sd_np(sd, "net.4.bias")
    bn1 = (sd_np(sd, "net.5.weight"), sd_np(sd, "net.5.bias"),
           sd_np(sd, "net.5.running_mean"), sd_np(sd, "net.5.running_var"))
    fc2_w, fc2_b = sd_np(sd, "net.8.weight"), sd_np(sd, "net.8.bias")

    fc0_w, fc0_b = fold_bn(fc0_w, fc0_b, *bn0)
    fc1_w, fc1_b = fold_bn(fc1_w, fc1_b, *bn1)

    rng = np.random.default_rng(GOLDEN_SEED)
    x = rng.uniform(0.0, 1.0, size=(1, N_FEAT)).astype(np.float32)
    # ratio col (idx 4) lives in 0-6 at runtime; make the golden realistic
    x[0, 4] *= 6.0
    with torch.no_grad():
        ref = m(torch.from_numpy(x)).numpy().reshape(-1)
    h = np.maximum(fc0_w @ x.reshape(-1) + fc0_b, 0.0)
    h = np.maximum(fc1_w @ h + fc1_b, 0.0)
    man = fc2_w @ h + fc2_b
    err = float(np.max(np.abs(man - ref)))
    assert err < 1e-4, f"AI-5 BN-fold mismatch: {err}"
    print(f"AI-5 BN-fold verified  max|folded-orig|={err:.2e}")

    hdr = ("/* ai5_diagnose_weights.h -- AI-5 Root-Cause Diagnoser MLP 27-32-16-9\n"
           " * AUTO-GENERATED by CIMC/model/ai5_rootcause/export_ai5_to_c.py -- do not edit.\n"
           " * BatchNorm folded into the Linears; trained float32 values in Flash (.rodata).\n"
           " * 9 classes diagnosed from the 27-D upstream-AI diagnostic vector (taxonomy.json). */\n"
           "#ifndef AI5_DIAGNOSE_WEIGHTS_H\n#define AI5_DIAGNOSE_WEIGHTS_H\n\n")
    hdr += "#define AI5_IN 27\n#define AI5_H0 32\n#define AI5_H1 16\n#define AI5_NCLS 9\n\n"
    # class-name table (ASCII) for the firmware to print
    hdr += "static const char *const AI5_CLASS_NAME[AI5_NCLS] = {\n"
    for nm in names:
        hdr += f'    "{nm}",\n'
    hdr += "};\n\n"
    hdr += carr("ai5_fc0_w", fc0_w)   # [32,27]
    hdr += carr("ai5_fc0_b", fc0_b)
    hdr += carr("ai5_fc1_w", fc1_w)   # [16,32]
    hdr += carr("ai5_fc1_b", fc1_b)
    hdr += carr("ai5_fc2_w", fc2_w)   # [9,16]
    hdr += carr("ai5_fc2_b", fc2_b)
    hdr += "\n#endif /* AI5_DIAGNOSE_WEIGHTS_H */\n"
    (OUT / "ai5_diagnose_weights.h").write_text(hdr, encoding="utf-8")
    print(f"  wrote {OUT / 'ai5_diagnose_weights.h'}")

    g = ("/* ai5_golden.h -- AI-5 golden vector for on-chip self-test.\n"
         " * AUTO-GENERATED by export_ai5_to_c.py. Fixed 27-D input + PyTorch eval-mode\n"
         " * logits; the firmware runs its C engine and checks max|err| < tol.\n"
         " * Included only by the self-test / host harness (keeps ai5_diagnose.c -Wall clean). */\n"
         "#ifndef AI5_GOLDEN_H\n#define AI5_GOLDEN_H\n\n")
    g += carr("g_ai5_input", x.reshape(-1))
    g += carr("g_ai5_logits", ref)
    g += "\n#endif /* AI5_GOLDEN_H */\n"
    (OUT / "ai5_golden.h").write_text(g, encoding="utf-8")
    print(f"  wrote {OUT / 'ai5_golden.h'}")
    print(f"  argmax(golden) = class {int(np.argmax(ref))} ({names[int(np.argmax(ref))]})")


if __name__ == "__main__":
    main()
