"""
export_crucible_to_c.py — AI-1 crucible CNN -> hand-written float C (CIMC)
==========================================================================
Loads crucible_cnn.pt, folds each BatchNorm2d into its (bias-less) Conv2d, and
emits firmware/ai_models_c/ai1_crucible_weights.h + a host golden header.

Self-checks before emitting: a numpy reimplementation that MIRRORS the planned
ai1_crucible.c engine (conv3x3 stride2 pad1 + ReLU, GAP, FC) is compared to the
torch eval-mode model — if they match (<1e-4) the C engine math is proven correct.

No fabricated constants: every value is a trained weight or a folded-BN derivative.

Run:  cd CIMC/model/ai1_vision_cnn && python export_crucible_to_c.py
"""

import json
from pathlib import Path

import numpy as np
import torch

from crucible_cnn import CrucibleCNN, CLASS_NAMES, IN_HW, N_CLS

HERE = Path(__file__).parent
OUT = HERE.parent.parent / "firmware" / "ai_models_c"
HOST = HERE.parent / "host_test"
GOLDEN_SEED = 4321
EPS = 1e-5


def carr(name, arr):
    flat = np.asarray(arr, dtype=np.float32).reshape(-1)
    vals = ", ".join(f"{float(v):.8e}f" for v in flat)
    return f"static const float {name}[{flat.size}] = {{ {vals} }};\n"


def fold_conv_bn(cw, gamma, beta, mean, var):
    """Conv2d(no bias)+BN2d -> folded (W', b'). cw:[O,I,3,3]."""
    scale = gamma / np.sqrt(var + EPS)            # [O]
    Wf = cw * scale[:, None, None, None]
    bf = beta - mean * scale
    return Wf.astype(np.float32), bf.astype(np.float32)


def np_conv3x3s2_relu(x, w, b):
    """Mirror the C engine. x:[IC,IH,IW], w:[OC,IC,3,3], b:[OC] -> relu([OC,OH,OW])."""
    IC, IH, IW = x.shape
    OC = w.shape[0]
    OH = (IH + 2 - 3) // 2 + 1
    OW = (IW + 2 - 3) // 2 + 1
    out = np.zeros((OC, OH, OW), dtype=np.float32)
    for oc in range(OC):
        for oy in range(OH):
            for ox in range(OW):
                acc = b[oc]
                for ic in range(IC):
                    for ky in range(3):
                        iy = oy * 2 + ky - 1
                        if iy < 0 or iy >= IH:
                            continue
                        for kx in range(3):
                            ix = ox * 2 + kx - 1
                            if ix < 0 or ix >= IW:
                                continue
                            acc += w[oc, ic, ky, kx] * x[ic, iy, ix]
                out[oc, oy, ox] = max(acc, 0.0)
    return out


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    HOST.mkdir(parents=True, exist_ok=True)
    sd = torch.load(HERE / "crucible_cnn.pt", map_location="cpu", weights_only=True)
    m = CrucibleCNN(); m.load_state_dict(sd); m.eval()

    # fold each stage (features.{0,1,2,3}.{0=conv,1=bn})
    convs = []
    for st in range(4):
        cw = sd[f"features.{st}.0.weight"].numpy()
        g = sd[f"features.{st}.1.weight"].numpy()
        be = sd[f"features.{st}.1.bias"].numpy()
        mu = sd[f"features.{st}.1.running_mean"].numpy()
        va = sd[f"features.{st}.1.running_var"].numpy()
        convs.append(fold_conv_bn(cw, g, be, mu, va))
    fcw = sd["head.weight"].numpy().astype(np.float32)   # [N_CLS,32]
    fcb = sd["head.bias"].numpy().astype(np.float32)
    assert fcw.shape[0] == N_CLS, f"head out {fcw.shape[0]} != N_CLS {N_CLS}"

    # golden input + torch reference
    rng = np.random.default_rng(GOLDEN_SEED)
    x = rng.uniform(0.0, 1.0, size=(3, IN_HW, IN_HW)).astype(np.float32)
    with torch.no_grad():
        ref = m(torch.from_numpy(x)[None]).numpy().reshape(-1)

    # numpy forward mirroring the C engine, using folded weights
    a = x
    for (w, b) in convs:
        a = np_conv3x3s2_relu(a, w, b)
    g = a.mean(axis=(1, 2))                       # GAP -> [32]
    man = (fcw @ g + fcb).astype(np.float32)
    err = float(np.max(np.abs(man - ref)))
    print(f"folded-numpy vs torch  max|err| = {err:.3e}")
    assert err < 1e-4, f"BN-fold / engine-math mismatch: {err}"

    # ---- Class Activation Map (CAM) for the predicted class --------------------
    # AI-1 ends in GAP->FC, so CAM is forward-only (no backward): for the argmax
    # class, CAM[h,w] = sum_k fc_w[cls,k] * conv3_featmap[k,h,w]. ReLU + max-norm to
    # [0,1] for display. a is [32,4,4]. This is the on-chip B3 explainability backend.
    cam_cls = int(np.argmax(man))
    cam = np.tensordot(fcw[cam_cls], a, axes=(0, 0)).astype(np.float32)   # [4,4]
    cam = np.maximum(cam, 0.0)
    cmax = float(cam.max())
    if cmax > 0.0:
        cam = cam / cmax
    cam16 = cam.reshape(-1).astype(np.float32)    # [16] row-major (h*4+w)

    # ---- emit weights header ----
    ch = [8, 16, 24, 32]
    cls_doc = " / ".join(f"{i} {c}" for i, c in enumerate(CLASS_NAMES))
    s = (f"/* AI-1 crucible {N_CLS}-class CNN weights (BN folded into stride-2 convs)\n"
         " * AUTO-GENERATED by export_crucible_to_c.py — do not hand-edit.\n"
         f" * Classes: {cls_doc}.\n"
         f" * in 3x64x64 ->[c3s2p1]8x32x32 ->16x16x16 ->24x8x8 ->32x4x4 ->GAP ->FC{N_CLS}.\n */\n"
         "#ifndef AI1_CRUCIBLE_WEIGHTS_H\n#define AI1_CRUCIBLE_WEIGHTS_H\n\n"
         f"#define CRU_IN_CH 3\n#define CRU_IN_HW 64\n#define CRU_NCLS {N_CLS}\n"
         f"#define CRU_C0 {ch[0]}\n#define CRU_C1 {ch[1]}\n#define CRU_C2 {ch[2]}\n#define CRU_C3 {ch[3]}\n\n")
    for st, (w, b) in enumerate(convs):
        s += carr(f"cru_conv{st}_w", w)   # [O,I,3,3]
        s += carr(f"cru_conv{st}_b", b)   # [O]
    s += carr("cru_fc_w", fcw)            # [N_CLS,32]
    s += carr("cru_fc_b", fcb)            # [N_CLS]
    s += "\n#endif /* AI1_CRUCIBLE_WEIGHTS_H */\n"
    (OUT / "ai1_crucible_weights.h").write_text(s, encoding="utf-8")
    print(f"  wrote {OUT / 'ai1_crucible_weights.h'}")

    # ---- emit golden (input + torch-expected logits + GAP embedding) ----
    # g (the numpy GAP) is what both the C engine and the AI-1b NCM consume; it
    # tracks torch's internal GAP to the same <1e-4 the logits do (FC is linear).
    sg = ("/* golden for ai1_crucible engine: input + torch logits + 32-D GAP embedding.\n"
          " * AUTO-GENERATED by export_crucible_to_c.py. Used by the on-chip self-test\n"
          " * (firmware/ai_models_c/ai_selftest.c) AND the host regression. */\n"
          "#ifndef AI1_CRUCIBLE_GOLDEN_H\n#define AI1_CRUCIBLE_GOLDEN_H\n\n")
    sg += carr("cru_g_input", x)          # [3*64*64]
    sg += carr("cru_g_logits", ref)       # [4]
    sg += carr("cru_g_emb", g)            # [32] GAP embedding (NCM input)
    sg += f"static const int cru_g_cam_cls = {cam_cls};\n"
    sg += carr("cru_g_cam", cam16)        # [16] CAM heatmap (ReLU+max-norm) for cls
    sg += "\n#endif /* AI1_CRUCIBLE_GOLDEN_H */\n"
    # on-chip copy (ai_selftest.c includes it) + host regression copy
    (OUT / "ai1_crucible_golden.h").write_text(sg, encoding="utf-8")
    (HOST / "ai1_crucible_golden.h").write_text(sg, encoding="utf-8")
    print(f"  wrote {OUT / 'ai1_crucible_golden.h'} (+host)  (torch logits={np.round(ref,3)})")

    cfg = json.loads((HERE / "crucible_config.json").read_text(encoding="utf-8")) \
        if (HERE / "crucible_config.json").exists() else {}
    print(f"  data_source={cfg.get('data_source','?')} val_acc={cfg.get('val_acc','?')} "
          f"class_order={CLASS_NAMES}")


if __name__ == "__main__":
    main()
