#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
import numpy as np
from evaluate_support_exact_v3 import canonical_bytes,sha256_file,write_json
CID="CAND-S-037";SEEDS=(20260801,20260802,20260803)
def metrics(y:np.ndarray,score:np.ndarray,qid:np.ndarray,stale:np.ndarray)->dict[str,float]:
 n=[];m=[]
 for q in np.unique(qid):
  ix=np.flatnonzero(qid==q);order=ix[np.argsort(-score[ix],kind="mergesort")];rel=y[order].astype(float);count=int(y[ix].sum());top=rel[:10];disc=1/np.log2(np.arange(2,len(top)+2));n.append(float(np.sum(top*disc))/max(float(np.sum(disc[:min(count,10)])),1e-12));pos=np.flatnonzero(rel);m.append(1/float(pos[0]+1))
 r={"ndcg_at_10":float(np.mean(n)),"mrr":float(np.mean(m)),"stale_evidence_rejection_recall":float(np.mean(score[stale.astype(bool)]<.5))};r["composite"]=float(np.mean(list(r.values())));return r
def rebuild(out:Path)->str:
 rec=[{"path":str(p.relative_to(out)).replace("\\","/"),"bytes":p.stat().st_size,"sha256":sha256_file(p)} for p in sorted(x for x in out.rglob("*") if x.is_file() and x.name!="artifact_manifest.json")];h=hashlib.sha256(canonical_bytes(rec)).hexdigest();write_json(out/"artifact_manifest.json",{"schema":"cimc.forge200.artifact-manifest.v1","records":rec,"content_root_sha256":h});return h
def main()->int:
 a=argparse.ArgumentParser();a.add_argument("--root",type=Path,required=True);a.add_argument("--artifact-root",type=Path,required=True);a.add_argument("--output",type=Path,required=True);args=a.parse_args();root=args.root.resolve();out=args.artifact_root.resolve()/CID;e=np.load(out/"three_seed_test_predictions.npz",allow_pickle=False);y=e["y"].astype(int);qid=e["query_id"].astype(np.int64);stale=e["stale_label"].astype(np.uint8);base=metrics(y,e["baseline_score"],qid,stale);seeds=[{"seed":s,**metrics(y,e[f"seed_{s}"][:,1],qid,stale)} for s in SEEDS];quant=metrics(y,e["quantized_best_seed"][:,1],qid,stale);vals=np.asarray([x["composite"] for x in seeds]);g=json.loads((out/"eval_grouped.json").read_text(encoding="utf-8"));best=next(x for x in seeds if x["seed"]==int(g["best_seed"]));delta=best["composite"]-quant["composite"];mean_pass=float(vals.mean())>base["composite"]+1e-6;qp=delta<=.02;status="PASS_CONTRACT_BASELINE_BOARD_PENDING" if mean_pass and qp else "FAIL_CONTRACT_BASELINE";r={"schema":"cimc.forge200.s037-exact-evaluation.v1","status":status,"candidate_id":CID,"baseline":base,"seed_reports":seeds,"quantized_best_seed":quant,"three_seed_mean_composite":float(vals.mean()),"three_seed_variance_composite":float(vals.var()),"three_seed_worst_composite":float(vals.min()),"aggregate_mean_beats_preregistered_baseline":mean_pass,"individual_seed_baseline_results_reported_not_release_gate":[bool(v>base["composite"]+1e-6) for v in vals],"quantized_best_seed_metric_delta":delta,"quantization_pass":qp,"dataset_sha256":sha256_file(root/"data"/"staged_s037_exact_v1"/f"{CID}.npz"),"authority":0,"board_accepted":False,"countable_model":False};write_json(out/"contract_exact_evaluation.v1.json",r);pp=out/"promotion_receipt.json";pr=json.loads(pp.read_text(encoding="utf-8"));pr.update({"status":"HOST_GPU_TRAINED_CONTRACT_BASELINE_PASS_BOARD_PENDING" if status.startswith("PASS") else "HOST_GPU_REJECTED_CONTRACT_BASELINE","exact_contract_baseline_pending":not status.startswith("PASS"),"contract_evaluation_sha256":sha256_file(out/"contract_exact_evaluation.v1.json"),"authority":0,"board_accepted":False,"countable_model":False});write_json(pp,pr);r["artifact_content_root_sha256"]=rebuild(out);write_json(args.output,r);print(json.dumps({"status":status,"mean":float(vals.mean()),"worst":float(vals.min()),"baseline":base["composite"],"quantization_pass":qp},sort_keys=True));return 0 if status.startswith("PASS") else 2
if __name__=="__main__":raise SystemExit(main())
