#!/usr/bin/env python3
"""Generate an LVGL 8.3 one-bit subset font from a user-supplied OFL font."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True,
                        help="OFL-licensed Noto/Source Han TTF or TTC")
    parser.add_argument("--vocab", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--pixels", type=int, default=16)
    parser.add_argument("--threshold", type=int, default=110)
    args = parser.parse_args()
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError as exc:
        raise SystemExit("Pillow is required: python -m pip install Pillow") from exc

    font_path = args.font.resolve()
    vocab_path = args.vocab.resolve()
    if not font_path.is_file() or not vocab_path.is_file():
        raise SystemExit("--font and --vocab must be existing files")
    lowered = font_path.name.lower()
    if not any(name in lowered for name in ("noto", "sourcehan", "source-han")):
        raise SystemExit("Use a reviewed OFL Noto/Source Han font; see LICENSES/OFL-1.1.txt")

    vocab = json.loads(vocab_path.read_text(encoding="utf-8"))
    chars = {chr(codepoint) for codepoint in range(0x20, 0x7F)}
    for token in vocab["id2tok"]:
        if isinstance(token, str) and not token.startswith("@") and token not in {"<pad>", "<bos>", "<sep>", "<eos>"}:
            chars.update(token)
    codepoints = sorted(ord(char) for char in chars)
    font = ImageFont.truetype(str(font_path), args.pixels)
    ascent, descent = font.getmetrics()
    bitmap = bytearray()
    descriptors = []
    for codepoint in codepoints:
        char = chr(codepoint)
        left, top, right, bottom = font.getbbox(char)
        width, height = right - left, bottom - top
        advance = int(round(font.getlength(char) * 16))
        start = len(bitmap)
        bits: list[int] = []
        if width > 0 and height > 0:
            image = Image.new("L", (width, height), 0)
            ImageDraw.Draw(image).text((-left, -top), char, fill=255, font=font)
            pixels = image.load()
            bits = [1 if pixels[x, y] >= args.threshold else 0 for y in range(height) for x in range(width)]
            for index in range(0, len(bits), 8):
                value = 0
                for offset in range(8):
                    value = (value << 1) | (bits[index + offset] if index + offset < len(bits) else 0)
                bitmap.append(value)
        descriptors.append((start, advance, width, height, left, ascent - bottom))

    base = codepoints[0]
    offsets = [codepoint - base for codepoint in codepoints]
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0",
        " * AUTO-GENERATED by tools/generate_cjk_font.py; do not edit.",
        f" * Source font: {font_path.name}; SHA-256: {sha256(font_path)}",
        " * Verify the source font's OFL-1.1 notice before distribution. */",
        '#include "lvgl.h"', "",
        f"static LV_ATTRIBUTE_LARGE_CONST const uint8_t cn_glyph_bitmap[{len(bitmap)}] = {{",
    ]
    for index in range(0, len(bitmap), 20):
        lines.append("    " + ",".join(f"0x{value:02X}" for value in bitmap[index:index + 20]) + ",")
    lines.extend(["};", "", "static const lv_font_fmt_txt_glyph_dsc_t cn_glyph_dsc[] = {",
                  "    {.bitmap_index=0,.adv_w=0,.box_w=0,.box_h=0,.ofs_x=0,.ofs_y=0},"])
    for item in descriptors:
        lines.append("    {.bitmap_index=%d,.adv_w=%d,.box_w=%d,.box_h=%d,.ofs_x=%d,.ofs_y=%d}," % item)
    lines.extend(["};", "", f"static const uint16_t cn_unicode_list[{len(offsets)}] = {{"])
    for index in range(0, len(offsets), 16):
        lines.append("    " + ",".join(str(value) for value in offsets[index:index + 16]) + ",")
    lines.extend([
        "};", "",
        "static const lv_font_fmt_txt_cmap_t cn_cmaps[] = {{",
        f"    .range_start={base},.range_length={offsets[-1] + 1},.glyph_id_start=1,",
        f"    .unicode_list=cn_unicode_list,.glyph_id_ofs_list=NULL,.list_length={len(offsets)},",
        "    .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}};",
        "#if LV_VERSION_CHECK(8,0,0)", "static lv_font_fmt_txt_glyph_cache_t cn_cache;", "#endif",
        "static const lv_font_fmt_txt_dsc_t cn_font_dsc={",
        "    .glyph_bitmap=cn_glyph_bitmap,.glyph_dsc=cn_glyph_dsc,.cmaps=cn_cmaps,",
        "    .kern_dsc=NULL,.kern_scale=0,.cmap_num=1,.bpp=1,.kern_classes=0,.bitmap_format=0,",
        "#if LV_VERSION_CHECK(8,0,0)", "    .cache=&cn_cache", "#endif", "};",
        "#if LV_VERSION_CHECK(8,0,0)", "const lv_font_t lab_font_cn16={", "#else", "lv_font_t lab_font_cn16={", "#endif",
        "    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt,",
        "    .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,",
        f"    .line_height={ascent + descent},.base_line={descent},.subpx=LV_FONT_SUBPX_NONE,",
        "    .underline_position=-2,.underline_thickness=1,.dsc=&cn_font_dsc};",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.output}: {len(codepoints)} glyphs, {len(bitmap)} bitmap bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

