#!/usr/bin/env python3
"""Generate SIM_ONLY FTIR cure-state spectra for P104."""
from __future__ import annotations
import argparse,csv,hashlib,json
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
from stage_matbench_experimental_v1 import canonical_bytes,sha256_file,write_json
SEED=20260803;BINS=64;FAMILIES=100;PER=40;SPLIT_NAMES=("train","validation","test")
def split_for(g):
 b=int(hashlib.sha256(g.encode("ascii")).hexdigest()[:8],16)%100;return 0 if b<70 else 1 if b<85 else 2
def gaussian(grid,center,width):return np.exp(-.5*((grid-center)/width)**2)
def main():
 p=argparse.ArgumentParser();p.add_argument("--root",type=Path,default=Path(__file__).resolve().parents[1]);a=p.parse_args();root=a.root.resolve();rng=np.random.default_rng(SEED);grid=np.linspace(600.,1800.,BINS);x=[];y=[];label=[];ratio=[];groups=[];splits=[];manifest=[]
 for fi in range(FAMILIES):
  g=f"FTIR-RESIN-{fi:03d}";react=float(rng.uniform(850.,1050.));reference=float(rng.uniform(1450.,1650.));product=float(rng.uniform(1100.,1350.));oxid=float(rng.uniform(1650.,1780.));width=float(rng.uniform(18.,55.));react_amp=float(rng.uniform(.7,1.6));ref_amp=float(rng.uniform(.5,1.4));nonlinear=float(rng.uniform(.7,1.8));code=split_for(g);manifest.append({"family":g,"reactive_peak_cm1":react,"reference_peak_cm1":reference,"product_peak_cm1":product,"oxidation_peak_cm1":oxid,"split":SPLIT_NAMES[code]})
  for _ in range(PER):
   alpha=float(rng.uniform(.18,1.));temperature=float(rng.uniform(25.,220.));shift=.025*(temperature-25.);spec=.08+.00003*(grid-1200.)+react_amp*(1-alpha)**nonlinear*gaussian(grid,react+shift,width)+ref_amp*(1+.08*alpha)*gaussian(grid,reference+.3*shift,width*1.1)+1.1*alpha**1.4*gaussian(grid,product-.2*shift,width*.9)+1.5*max(alpha-.86,0.)*(1+(temperature-25.)/300.)*gaussian(grid,oxid+shift,width*.75);spec=np.maximum(spec+rng.normal(0,.008,size=BINS),0.);ri=int(np.argmin(abs(grid-react)));rfi=int(np.argmin(abs(grid-reference)));peak_ratio=float(spec[ri]/max(spec[rfi],1e-6));cls=0 if alpha<.62 else 1 if alpha<.9 else 2;x.append(np.concatenate((spec,np.asarray([temperature/250.,react/1800.,reference/1800.,product/1800.,oxid/1800.]))).astype(np.float32));y.append(alpha);label.append(cls);ratio.append(peak_ratio);groups.append(g);splits.append(code)
 x=np.asarray(x,np.float32);y=np.asarray(y,np.float32);label=np.asarray(label,np.int8);ratio=np.asarray(ratio,np.float32);group=np.asarray(groups);split=np.asarray(splits,np.int8);train=split==0;design=np.column_stack((ratio[train],np.ones(np.sum(train))));coef=np.linalg.lstsq(design,y[train],rcond=None)[0];baseline_alpha=np.clip(coef[0]*ratio+coef[1],0,1).astype(np.float32);baseline_class=np.where(baseline_alpha<.62,0,np.where(baseline_alpha<.9,1,2)).astype(np.int8);sets={c:set(group[split==c]) for c in (0,1,2)};overlap=sum(len(sets[l]&sets[r]) for l,r in ((0,1),(0,2),(1,2)));counts={SPLIT_NAMES[c]:int(np.sum(split==c)) for c in (0,1,2)};classes={SPLIT_NAMES[c]:{str(k):int(np.sum(label[split==c]==k)) for k in range(3)} for c in range(3)}
 if overlap or min(counts.values())<400 or min(min(v.values()) for v in classes.values())<40:raise RuntimeError(f"DATA_GATE:{overlap}:{counts}:{classes}")
 with (root/"contracts"/"candidate_task_contracts_244.v1.tsv").open("r",encoding="utf-8-sig",newline="") as h:contracts={r["candidate_id"]:r for r in csv.DictReader(h,delimiter="\t")}
 cid="CAND-P-104";out=root/"data"/"staged_physics_p104_exact_v1"/f"{cid}.npz";out.parent.mkdir(parents=True,exist_ok=True);np.savez_compressed(out,x=x,y=y,label=label,baseline_alpha=baseline_alpha,baseline_class=baseline_class,group=group,split=split);c=contracts[cid];meta={"schema":"cimc.forge200.physics-p104-exact-dataset.v1","created_at_utc":datetime.now(timezone.utc).isoformat(),"status":"PASS","candidate_id":cid,"truth_class":"PHYSICS_SIM","public_claim_scope":"SIM_ONLY","simulator":"TEAM_OWNED_MULTI_PEAK_FTIR_CURE_OXIDATION_SPECTRUM_SIMULATOR","generation_seed":SEED,"records":len(y),"spectrum_bins":BINS,"families":FAMILIES,"family_manifest_root_sha256":hashlib.sha256(canonical_bytes(manifest)).hexdigest(),"split_counts":counts,"class_counts":classes,"cross_split_component_overlap":overlap,"cross_split_family_overlap":overlap,"baseline_execution":"TRAIN_ONLY_GLOBAL_AFFINE_SINGLE_REACTIVE_TO_REFERENCE_PEAK_RATIO","baseline_coefficients":[float(v) for v in coef],"input_contract":c["input_contract"],"target_label":c["target_label"],"primary_metric":c["primary_metric"],"parameter_cap":c["parameter_cap"],"task_contract_sha256":hashlib.sha256(canonical_bytes(c)).hexdigest(),"source_license":"TEAM_OWNED_GENERATED_SIMULATION","experimental_records":0,"teacher_outputs":0,"authority":0,"board_accepted":False,"countable_model":False,"generator_sha256":sha256_file(Path(__file__)),"sha256":sha256_file(out)};write_json(out.with_suffix(".metadata.json"),meta);write_json(root/"evidence"/"physics_p104_exact_staging.v1.json",{"schema":"cimc.forge200.physics-p104-exact-staging.v1","created_at_utc":datetime.now(timezone.utc).isoformat(),"status":"PASS","record":meta,"authority_nonzero":0,"board_actions":0});print(json.dumps({"status":"PASS","records":len(y),"split_counts":counts,"class_counts":classes},sort_keys=True));return 0
if __name__=="__main__":raise SystemExit(main())
